[package]
name = "cmdle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12"
clap = { version = "3.1", features = ["derive"] }
chrono = "0.4"
colored = "2.0"
