[tasks.setup]
script_runner = "@duckscript"
script = '''
echo "Setting up debug profile..."

mkdir target/debug
cp goals.json target/debug/goals.json
cp guesses.json target/debug/guesses.json

echo "Setting up release profile..."

mkdir target/release
cp goals.json target/release/goals.json
cp guesses.json target/release/guesses.json
'''

[tasks.pack]
description = "Packages the files into a zip folder."
script_runner = "@duckscript"
script = '''
exec cargo build --release
mkdir target/packed/cmdle
cp target/release/cmdle.exe target/packed/cmdle/cmdle.exe
cp goals.json target/packed/cmdle/goals.json
cp guesses.json target/packed/cmdle/guesses.json
cd target/packed/cmdle
exec 7z a -tzip ../cmdle.zip goals.json guesses.json cmdle.exe
'''
